version: '3.3'

services:
  grassapi:
    # image: epinux/fastapi:latest
    image: epinux/grassapi:latest
    build:
      context: ./docker
    environment:
      DEBUG: 1
      PYTHONUNBUFFERED: 1
      LOGLEVEL: DEBUG
      FORWARDED_ALLOW_IPS: "*"
    hostname: grassapi
    volumes:
      - ./apps/grassapp:/app
      - ./grassdata:/app/grassdata
    ports:
      - 80:80
